### ISSUE TITLE
No styling of content in <pre> elements

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/o-layout#92]
## What

There is no styling of content inside of `<pre><code>` tags.

## Details

![image](https://user-images.githubusercontent.com/51677/58082791-99b85b00-7baf-11e9-91ed-1edc456ee163.png)

See https://customer-products.in.ft.com/wiki/How-we-manage-our-GitHub-repositories#how-can-we-tell-which-repositories-are-ours.

## Suggestion

Keep it light.

```scss
  :not(pre) > code {
    font-style: italic;
  }

  pre {
    padding: 0.8rem;
    margin-top: 0;
    margin-bottom: 1rem;
    word-wrap: normal;
    border: solid 1px $border-color;
    border-radius: 0.3rem;

    > code {
      padding: 0;
      margin: 0;
      font-size: 1.1rem;
      word-break: normal;
      white-space: pre;
      background: transparent;
      border: 0;
    }
  }
```

I quite liked reading https://www.kizu.ru/styling-inline-code/ for inline code.
